### PR TITLE
[Implement] subarray

### PR DESCRIPTION
**Pull request by jtenner**
Original `.subarray()` implementation does not return `Buffer`. It returns `Uint8Array`.

Copied and optimized for our purposes from the `SUBARRAY` macro. Any problems? @dcodeIO

### CODE REVIEW

**Comment by dcodeIO** [comment]
Can this maybe reuse the Uint8Array implementation, like in `changetype<Buffer>(super.subarray(...))`? **Edit:** Hmm, no, the id wouldn't match.

**Comment by jtenner** [comment]
@dcodeIO We could reuse the parent class's version. All we have to do is change the rtId value.

```ts
let result = super.subarray(...);
let block = changetype<BLOCK>(changetype<usize>(result) - BLOCK_OFFSET); // whatever this is
block.rtId = idOf<Buffer>();
return result;
```

**Comment by jtenner** [comment]
Best solution would just be to use the macro in the std lib but it's not exported.

**Comment by jtenner** [comment]
Unless there are any problems with this implementation, can we pull this?

**Comment by jtenner** [comment]
I will leave this as implemented for now because it's technically faster than:

```ts
let out = super.subarray(start, end);
changetype<BLOCK>(changetype<usize>(out) - BLOCK_OFFSET).rtId = idof<Buffer>();
return out;
```

**Comment by MaxGraey** [comment]
How about use:
```ts
public subarray(begin: i32 = 0, end: i32 = 0x7fffffff): Buffer {
  return SUBARRAY<Buffer, u8>(this, begin, end);
}
```
And make ```SUBARRAY``` macro from `typedarray.ts` exportable.

**Comment by MaxGraey** [comment]
Or even better move all typedarray's macros to new `std/assembly/util/typedarray.ts` file

**Comment by jtenner** [comment]
@MaxGraey That would be nice, but I can't use the `SUBARRAY` function unless it's exported by the std library. Will have to wait until that changes.

**Review by dcodeIO — APPROVED** [review]

**Comment by dcodeIO** [comment]
Seems fine this way.

**Comment by jtenner** [comment]
If assemblyscript/assemblyscript#740 pulls, then I will refactor the current implementation to contain the utility functions.

**Pull request merged**
