### PR TITLE
[Cleanup] readInt8's offset defaults to 0

### PR DESCRIPTION
**Pull request by RedDwarfian**
Made `readInt8` `offset` default to `0`, and modified casting to use stdlib's `<u32>offset` syntax.

### CODE REVIEW

**Comment by jtenner** [comment]
@dcodeio looks like he's still learning how to use git :).

Think we can accept this instead?

**Comment by jtenner** [comment]
@RedDwarfian you can close this yourself when you're ready.

**Comment by dcodeIO** [comment]
All good. Would usually recommend adding these function all at once to reduce reviewing/merging overhead, but if you're ok with it then I'm as well. Great to see a new contributor in the first place :)

**Comment by jtenner** [comment]
The goal was to help him get comfortable with git and writing assemblyscript functions. Lots of practice :)

**Pull request closed without merging**
